### ISSUE TITLE
"Delete folder" dialog does not show folder name

### ISSUE THREAD

**Issue by shoce** [ipfs/ipfs-webui#1258]
**Is your feature request related to a problem? Please describe.**
The dialog for deleting a folder does not show the name of the folder to be deleted.

**Describe the solution you'd like**
 If the name of the folder/file will be shown it would feel much more comfortable to push "Delete".

**Additional context**

![](https://user-images.githubusercontent.com/261885/67031437-29e2d800-f12f-11e9-9c40-1ecc5a32a930.png)

**Versions**:
ipfs-desktop 0.9.5
macOS 10.15

**Comment by rslnx** [comment]
This is a copy of https://github.com/ipfs-shipyard/ipfs-desktop/issues/1197. Will need to delete a non-relevant but still not sure which one is.

**Comment by hacdias** [comment]
I closed the one in Desktop side as this is where it is relevant :) Thanks for filing this

**Comment by jessicaschilling** [comment]
A few notes ...
- This dialog appears whether you're deleting an item (a file, a folder, whatever) via right-click action OR via the multi-select boxes that appear on the left of the files grid.
- If you're using the multi-select boxes and then choose "Delete" from the bar that appears at the bottom of the screen, it's fairly apparent which items you're trying to delete, because they're highlighted. I'll therefore make the assumption that we're less concerned about this scenario.

AFAIK, we can't change behavior based on whether the user is trying to delete via right-click versus via multi-select action. On the other hand, we *could* take the approach of listing the name of the item to be deleted *only* if the user is asking to delete just one item (perhaps just "Are you sure you want to delete this file (catphoto.gif)?"). However, that results in somewhat inconsistent behavior in the scenario of bullet #2 above: you see the file name in the dialog when you've only ticked one multi-select box, but the generic "Are you sure you want to delete these items?" if you check more than one.

Would be curious to hear thoughts from @lidel @hacdias @rafaelramalho19 and any others when they have the time.

**Comment by lidel** [comment]
- I am for showing the name when a single item is deleted (no matter if it was via context or via checkbox + bottom menu)

- When multiple items are deleted  its ok to show just the [item count](https://user-images.githubusercontent.com/157609/81851132-475b1180-9559-11ea-96a9-3a2a621bc7cd.png), because user used checkboxes just moments ago.

**Comment by jessicaschilling** [comment]
@lidel Agree. @rafaelramalho19 or @hacdias, any thoughts?

**Comment by hacdias** [comment]
I agree with what @lidel's said. Name for single items, count for multiple files.

**Comment by rafaelramalho19** [comment]
Also agree with Lidel's suggestion :)

**Comment by jessicaschilling** [comment]
@rafaelramalho19, I know your plate is getting full, but do you think you'd be able to take this on?
Or, I know I'm not supposed to distract @hacdias but if you wanted to pick off something small, this would be a good choice. 😊

**Comment by rafaelramalho19** [comment]
I'll try to pick this up soon 😄

**Comment by jessicaschilling** [comment]
Quick note: We're making some other related changes to the "delete" modal in https://github.com/ipfs-shipyard/ipfs-webui/pull/1644. Added a note in that PR suggesting we close this issue in that work.

**Comment by shoce** [comment]
> Quick note: We're making some other related changes to the "delete" modal in #1644. Added a note in that PR suggesting we close this issue in that work.

Hey @jessicaschilling thanks, i think it would be fine to include this change into #1644. The only screenshot i see in #1644 does not show the name of the object to be removed yet.

**Comment by jessicaschilling** [comment]
@shoce Thanks - added a note to that effect in #1644. Probably no need to update the screenshot but I will do if @rafaelramalho19 asks - he's taking this one over the finish line 😊
