### ISSUE TITLE
Advanced section should stay open unless the user chooses to close it.

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-webui#1693]
**Describe the bug**
When open, the Status > Advanced block toggle is triggered if i click anywhere inside it. It's frustrating when trying to copy some text from it.

Ideally it would behave like a regular `<details>` element, and only close if the user clicks on the summary.

![advanced-collapse](https://user-images.githubusercontent.com/58871/99917856-edf34c80-2d0a-11eb-8a59-185fee6307a8.gif)

**Comment by jessicaschilling** [comment]
@rafaelramalho19, can you please have a look at this once you're done with file overwrite stuff? Thank you!

**Comment by jessicaschilling** [comment]
It looks like `onClick={handleSummaryClick}` is causing the collapse behavior:
https://github.com/ipfs-shipyard/ipfs-webui/blob/a787562329791fca8d8dec5e3d8763ba3310581c/src/status/NodeInfoAdvanced.js#L51

I believe this was added so that clicking the ![image](https://user-images.githubusercontent.com/1507828/100028381-05cedd00-2dac-11eb-855a-db210814e84d.png) icon in the top right of the UI would take the user to the Settings page with `Advanced` expanded, but the logic for *why* we wanted this expanded eludes me. @lidel or @rafaelramalho19, any idea? Asking because I'm not sure if it's worth finding a fix as opposed to just removing `handleSummaryClick`.

**Comment by jessicaschilling** [comment]
This was raised again in #1711. Can we please prioritize once pinning work is done?
