### ISSUE TITLE
Preview link broken if using non default port

### ISSUE THREAD

**Issue by msfeldstein** [ipfs/ipfs-webui#1715]
- OS: macOS 10.15.6
 - Version of IPFS Desktop: 0.13.2

**Describe the bug**
If IPFS Desktop is not using the default port (8080) the link to preview it still uses 8080, which is incorrect.  I'm running another service that's holding port 8080 (nginx) so IPFS will use 8081 instead.  I see `"Gateway": "/ip4/127.0.0.1/tcp/8081",` in my config file.  When i click the link below it opens `http://localhost:8080/ipfs/<cid>` which is actually routed to nginx and I get a 404.  If I manually change the port in the url to 8081 things work correctly. 

<img width="1552" alt="Screen Shot 2020-12-31 at 3 17 11 PM" src="https://user-images.githubusercontent.com/161135/103430667-0701df80-4b8c-11eb-82ee-69dfb76b05ba.png">

**To Reproduce**
- Change the Gateway port in `~/.ipfs/config` to 8081 (`"Gateway": "/ip4/127.0.0.1/tcp/8081",`)
- Restart IPFS Desktop
- Try to open a pinned file, or any file via the localhost gateway api

**Screenshots**
<img width="1120" alt="Screen Shot 2020-12-31 at 3 20 58 PM" src="https://user-images.githubusercontent.com/161135/103430728-90b1ad00-4b8c-11eb-92e5-5ae295229801.png">

**Additional context**

[combined.log](https://github.com/ipfs-shipyard/ipfs-desktop/files/5758445/combined.log)
(error log empty)

**Comment by alx696** [comment]
@lidel It is better to support set port of public gateway port! With `v2.13.0` The public gateway can be set, but the port cannot be set.

Submit `https://ipfs.lilu.red:444`, check url is `https://ipfs.lilu.red/ipfs/bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe?now=1632573744950&filename=1x1.png`, [code not set port](https://github.com/ipfs/ipfs-webui/blob/main/src/bundles/gateway.js#L30)

In China, personal cannot use ports 80, 8080, and 443. The network service provider closed these ports. The important feature of IPFS is decentralization, so that everyone can enjoy the network equally. This restriction prevents the possibility of individuals providing gateways.

**Comment by SgtPooki** [comment]
I was unable to reproduce this using the webui provided by Kubo:

```
WebUI: http://127.0.0.1:5002/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8081
```

Nor with ipfs-desktop.

Is this still an issue @msfeldstein ?
