### ISSUE TITLE
IPFS errors / API error

### ISSUE THREAD

**Issue by TheTrueShadow** [ipfs/ipfs-webui#1749]
![Screenshot (135)](https://user-images.githubusercontent.com/80232013/110882950-b35cf200-82b0-11eb-8b82-1a12ee6ff364.png)
![Screenshot (136)](https://user-images.githubusercontent.com/80232013/110882952-b35cf200-82b0-11eb-8bf6-53094cd813eb.png)
![Screenshot (137)](https://user-images.githubusercontent.com/80232013/110882954-b3f58880-82b0-11eb-97dc-3241b46dfbc8.png)
![Screenshot (138)](https://user-images.githubusercontent.com/80232013/110883038-d7b8ce80-82b0-11eb-9553-dcabf4176843.png)
![Screenshot (139)](https://user-images.githubusercontent.com/80232013/110883102-f3bc7000-82b0-11eb-8c6c-c744e7e9aa32.png)
![Screenshot (140)](https://user-images.githubusercontent.com/80232013/110883302-426a0a00-82b1-11eb-9c98-d76d58291338.png)
![Screenshot (141)](https://user-images.githubusercontent.com/80232013/110883304-4302a080-82b1-11eb-8f76-020d1aae1fe0.png)
![Screenshot (142)](https://user-images.githubusercontent.com/80232013/110883305-4302a080-82b1-11eb-83dc-1e8d53062fca.png)
IPFS will let me upload but not view my node info
![image](https://user-images.githubusercontent.com/80232013/110883544-a8569180-82b1-11eb-996b-0a64a6fcb9b7.png)

**Comment by SgtPooki** [comment]
@TheTrueShadow There have been significant updates in all the tools you've included here since the issue was opened. I apologize that we were unable to be more responsive, but I believe many of the issues you experienced may be resolved, or at least provide more information in the error messages output.

If you are still running into issues, please open an issue using our github issue bug template (new issue, then just fill out the details) for each single issue you experience and we will do our best to assist you further. Thanks
