### ISSUE TITLE
Files: "Import from IPFS" with a name

### ISSUE THREAD

**Issue by bluelovers** [ipfs/ipfs-webui#1818]
**Is your feature request related to a problem? Please describe.**

current, if we import from ipfs

it will create name as cid, but hope can allow input a name, without rename it after import

![image](https://user-images.githubusercontent.com/167966/126035957-9d64446c-177b-4a5e-a121-fced2c4780aa.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hsn10** [comment]
Yes, this is important. It saves me a rename step after import.

**Comment by hsn10** [comment]
Also you can allow imports with specified filename. Currently these _pass_ check by frontend UI but _wont_ get imported

> /ipfs/QmTMJJBRAxJj7FApAFoS8QKtc1pZctJXqg6mWh8XffwXXn?filename=bigHORNS_SR.jpg

**Comment by lidel** [comment]
:+1:   for this, I think an optional "Name" field below the IPFS Path field  would do the trick:

- if Name is left empty, we use CID as a fallback (current behavior)
- if Name is provided, then we use it instead of  CID
- (nice to have) if path ends with `?filename=..` then  Name is filled automatically

I'm happy to review if someone has bandwidth to implement this :+1:
