### ISSUE TITLE
Switch publish-release-build.yml to CAR

### ISSUE THREAD

**Issue by aptalca** [ipfs/ipfs-webui#1847]
**Describe the bug**
Just a heads up (in case you haven't noticed already), the GitHub actions for the ci have been failing for the last few commits (js test) and the release binary upload action also failed in this repo.

**Comment by lidel** [comment]
Thanks for raising this.

Fixing E2E tests against js-ipfs is already tracked in https://github.com/ipfs/ipfs-webui/issues/1737

The job that attaches binaries failed due to unrelated reasons.

I believe we should rewrite it to read the latest release via https://api.github.com/repos/ipfs/ipfs-webui/releases/latest and then generate TAR and CAR by fetching the CID listed in Release notes. PR welcome.

**Comment by aptalca** [comment]
Looks like the tar file was created successfully, but the upload failed. Can you rerun that action from the github gui?

**Comment by lidel** [comment]
- The TAR failed to upload today again  – lacks a robust retry
- Ideally, we would remove TAR and only use verifiable CAR
- For now, attached both manually to [v2.14.0](https://github.com/ipfs/ipfs-webui/releases/tag/v2.14.0) (but we may gzip CAR when we automate this)

**Comment by SgtPooki** [comment]
I believe this should be resolved now as all our releases contain a CAR file
