### ISSUE TITLE
Error: No resolver found for codec "dag-json" (and dag-cbor)

### ISSUE THREAD

**Issue by ben221199** [ipfs/ipfs-webui#1923]
- OS: Windows
 - Version of IPFS Desktop: 0.20.5

**Describe the bug**
Not all codecs supported by the IPFS command-line are supported by IPFS desktop. See screenshot. It only shows `dag-json` but also `json` and some other codecs show the same error.

When making a CID using `ipfs dag put someData.json --store-codec=dag-json`, I get a CIDv1. Strange enough, `dag-json` is not in the list of `ipfs cid codecs`, but supported by `ipfs dag put`. When copying the received CID to IPFS Desktop, I get error from the screenshot that there is no resolver found for the codec.

**To Reproduce**
1. `ipfs cid codecs`
2. `notepad someData.json` and add some JSON data
3. `ipfs dag put someData.json --store-codec=dag-json`
4. Copy the received CID to IPFS Desktop and inspect it.
5. See error

**Expected behavior**
IPFS Desktop recognises that the CID is `dag-json`, so it should also view information about the content.

**Screenshots**
![image](https://user-images.githubusercontent.com/12856904/162975053-b7ccd9a6-5ae0-435e-9177-5ebdf3bf763e.png)

**Additional context**
_None._

**Comment by lidel** [comment]
@hacdias mind taking a look if we can add support for `dag-json` (and dag-cbor) CIDs?
 
-  We won't be able to open them  as filesystem, so "Browse" should be inactive for them, or open the same view as "Inspect" (ipld-explorer)

**Comment by hacdias** [comment]
@lidel just before I tackle this, isn't the fact that IPLD Explorer still uses the old microformats packages a blocker? And updating that is, in turn, blocked by migrating Web UI to the newer IPFS JS HTTP API version? Because the `@ipld/js-dag-json` should be incompatible with the old versions.

Refs:

- https://github.com/ipfs/ipfs-webui/pull/1840
- https://github.com/ipfs/ipfs-webui/issues/1798#issuecomment-910930951
- https://github.com/ipfs/ipld-explorer-components/issues/311#issuecomment-1094370144

If so, I may not have time to address this because of how large the scope can be at the moment.

**Comment by lidel** [comment]
@hacdias 

- IPLD Explorer does everything in userland – it will fetch block via `ipfs.block.get` and then parses it locally using own libs
  - due to this, I believe it is not blocked by js-ipfs-http-client upgrade –  I made it compatible with modern `block.get` in https://github.com/ipfs/ipld-explorer-components/commit/a9e86f491d0f377c88c6e3f4fa6ff99d15df0852 
- https://github.com/ipfs/ipld-explorer-components/pull/313 added modern [`multiformats`](https://www.npmjs.com/package/multiformats) as a dependency, so you should be able to use modern codes –  detect dag-json and dag-cbor codec in CIDv1, and special-case its parsing using the new libraries.

**Comment by hacdias** [comment]
@lidel here's a PR to add support for `dag-json`: https://github.com/ipfs/ipld-explorer-components/pull/319

`dag-cbor` is supposed to be working already. As you can see, I used [this converter](https://github.com/ipld/js-blockcodec-to-ipld-format) to make the new package be compatible with the old `ipld`. If there are other formats to be supported, or even if you want the old formats updated to the new packages, I can take care of that using the converter.

**Comment by hacdias** [comment]
@lidel so I've been _trying_ to tackle that and I've been running into this two issues:

1. We cannot use `ipfs.dag.import` on the tests because we don't have an enough updated version of the HTTP API (cc #1838)
2. `ipfs.dag.put` is failing with `HTTPError: Invalid byte while expecting start of value: 0xa2` which may be caused by mistach of go ipfs version and the HTTP client (see #3914).

I have been trying to find a workaround, without success. Any suggestions?

**Comment by lidel** [comment]
This was fixed upstream, and works in the latest webui:

> ![2022-12-06_01-31](https://user-images.githubusercontent.com/157609/205776486-a5c96e8d-a61f-4036-a1db-8e73b32336b5.png)

JSON / CBOR saga continues in: https://github.com/ipfs/kubo/pull/9335
