### ISSUE TITLE
Invalid version in release UI

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1984]
https://github.com/ipfs/ipfs-webui/releases/tag/v2.17.3 states CID `bafybeihfkeactw26tghz7m3puzh4zqlukvft2f7atfdc7t2qmqn2vszhc4` and that CID shows previous release version:

>  ![2022-07-21_14-17](https://user-images.githubusercontent.com/157609/180211646-c93f82df-086a-4b0d-a7e8-407daf01cafd.png)

**Comment by lidel** [comment]
Potential fix is to run build again, AFTER version bump but BEFORE changelog and CAR are generated:
-  https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package.jsons-version

**Comment by lidel** [comment]
@SgtPooki I'm marking this as P0 because we can't ship a release with invalid version in UI.

**Comment by hacdias** [comment]
#2000 removes the Web UI version for now. I think it's a good temporary solution. However, I think that after @SgtPooki comes back, we should at least make sure it says the correct revision. I agree that removing the Web UI version is fine overall since many people confuse it with Desktop / Kubo version.

**Comment by lidel** [comment]
https://github.com/ipfs/ipfs-webui/pull/2000 got merged, if we are ok with only having the revision (seems like improved UX for  ipfs-desktop users)  this can be closed. 

@SgtPooki your call.

**Comment by SgtPooki** [comment]
Yea I'm good with only having the revision on there. The only issue I see is that it could cause issues when users try to communicate bugs for specific versions, and when maintaining issues because we don't think about revisions as quickly as we do version numbers. So we will need to decode that revision every time. I'll leave this open and leave it as P2

**Comment by SgtPooki** [comment]
Going to close this and we can address this if it comes up again
