### ISSUE TITLE
Zero length file does not show weight

### ISSUE THREAD

**Issue by MarcelInTO** [ipfs/ipfs-webui#2017]
- OS: Windows
- Version of IPFS Desktop: 2.15.1

When browsing a folder of files (in the file section) where some files have been pinned and others have not, the pinned files do not show a size. The just show a "-".

**Expected behavior**
All files should show their size regardless of pin status.

**Screenshots**
![image](https://user-images.githubusercontent.com/5455478/186444582-64560b13-f063-4e3a-9d91-7e10cc4bc50a.png)

**Comment by hacdias** [comment]
After taking a look, this issue is not related to pinned files. The issue here is that a zero length file shows `-` instead of `0 B` on the size column.

To reproduce:

1. `touch blank_file`
2. `ipfs add blank_file` -> CID will be `QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH`
3. `ipfs cp /ipfs/QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH /blank_file`
4. See on IPFS Web UI
