### ISSUE TITLE
Differentiate between webui.ipfs.io and webui from kubo

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-webui#2078]
I think we can have an environment variable on the webui deployment with countly APP ID and then an APP ID that would be used if that env var is not set. webui.ipfs.io deployments would be able to override the hardcoded APP ID, and kubo usage would use the hardcoded one. This will allow us to proceed without being blocked on any Kubo changes for making this happen

**Comment by SgtPooki** [comment]
i'm realizing now that since we're deploying webui assets as a CID and updating DNSlink, that we can't simply set the env var as we would with a typical deployment. If we were to migrate to fleek for deployment, this could be resolved in the manner described in the issue description, but without that, we may need to do some client side logic to determine which env we're running on

**Comment by lidel** [comment]
You can inspect `window.location.origin` and if it includes `webui.ipfs` or `webui-ipfs` then you know it was loaded via DNSLink (either public HTTP server or local node). 

In similar fashion, you can detect when it was loaded via specific CID (`origin` or `pathname` will include CID). 

Based on that, you can assign different APP ID and initialize telemetry with it.

**Comment by SgtPooki** [comment]
it also looks like doing `var foo = await fetch('/webui', {method: 'HEAD'})` gives us pretty unique results:

1. Local run: `response.redirected === false` - it just works, and has 200 success... we should probably adjust dev server for this, but I think the below two items are the important ones.
2. kubo run: `reponse.redirected === true` - kubo redirects /webui to the CID listed. I believe this redirect is unique to kubo
3. webui.ipfs.io run: `throws 404` - makes sense 

Would this be a valid approach?

**Comment by lidel** [comment]
Yes, that will  work too. 

Might silently break if we ever change the way Kubo behaves, or we add `/webui` subdirectory to webui itself  for some reason, but you can always do the `window.location.origin.includes("webui-ipfs") || window.location.origin.includes("webui.ipfs")` first to guard against that

Note `-` and `.` and lack of TLD because  it can be loaded from various origins:
-  `http://webui.ipfs.io.ipns.localhost:8080/` and Brave's  `http://webui.ipfs.io.ipns.localhost:48080/`
-  `https://webui-ipfs-io.ipns.dweb.link/`
-  `https://webui.ipfs.tech` and matching gateway variants (if we ever move it away from .io)
