### ISSUE TITLE
Unable to remotely pin on Pinata with the WebUI

### ISSUE THREAD

**Issue by mariaa144** [ipfs/ipfs-webui#2096]
**Describe the bug**
When I try to remote pin using the webui I get an error and the pinning doesn't work. I have to go to Pinata web interface to pin manually. The remote pinning was working but after a recent update I started gettting the following error.

The error is: `Unable to set pinning at Pinata: HTTPError: reason: "INVALID_ORIGINS", details: "provider array entry: /ip4/10.117.144.19/udp/4001/quic-v1/p2p/xxxxx is not a valid peer multiaddr": 400 Bad Request`

**To Reproduce**
1. Setup remote pinning with Pinata
2. Try to pin a file
3. Notice error at the bottom of the webui

**Expected behavior**
The pinning should work and there shouldn't be an error.

**Desktop (please complete the following information):**
 - OS: Arch Linux (Garuda Linux)
 - Browser: Firedragon
 - Version: Revision 546fb5a

**Additional context**
I reached out to Pinata but the support person wasn't able to help me. She said if it was a problem with their service due to a new IPFS version then it would likely be fix sometime in the future.

**Comment by SgtPooki** [comment]
Hey @mariaa144 thanks for submitting this issue and your detailed descriptions. I'm sorry you're experiencing an issue with pinning your content. 

**What ipfs version are you connecting the webui to?** Kubo recently added support for the `quic` transport, which may not be supported by some services, but the webui should be able to handle this via graceful degradation of some sort. (we don't right now, which is why this **_is a bug_** in webui)

It looks like you're using at least Kubo 0.18.0 because of the transport in your provider array containing `quic-v1`. You can read more about the quic protocol changes at https://github.com/ipfs/kubo/releases/tag/v0.18.0

> QUICv1 and WebTransport config migration
> To support QUICv1 and WebTransport by default a new config migration (v13) is run which automatically adds entries in addresses-related fields:
> 
> Replace all /quic/webtransport to /quic-v1/webtransport.
For all /quic listeners, keep the Draft-29 listener, and on the same ip and port, add /quic-v1 and /quic-v1/webtransport listeners.

For a temporary fix, try one of the following:

1. Disable webtransport/quic when talking to pinata (you need to modify `~/.ipfs/config`, more descriptions about how this is enabled described at https://github.com/ipfs/kubo/releases/tag/v0.16.0#-webtransport-new-experimental-transport)
2. use kubo 0.17 or other ipfs daemon that doesn't have webtransport/quic enabled by default until Pinata does. 
    - This may require also updating your config, depending on how you're running the backing ipfs daemon for your webui instance.


I will mark this issue as a bug and investigate some mitigation methods in the meantime. Please let us know if you are able to workaround this successfully, and we will update you when we have more details.

**Comment by SgtPooki** [comment]
@mariaa144 I looked into this further, and AFAIK, Kubo should not be falling over on unknown protocols, and I think this is happening in the Pinata API server stack. I believe that Pinata will need to either update to the latest libraries or patch things similar to https://github.com/ipfs/ipfs-webui/blob/1cf2fe706d1f9ff7916d979748c0791627f1fe91/patches/multiaddr%2B8.1.2.patch#L1-L34. 

I reached out to the pinata team internally to discuss this and they will hopefully implement a fix soon. As for webui, the only fix I can think of to resolve this now, and in the future, is to remove protocols conditionally when they fail at the service level, but that should be done on the service side. 

I think this issue should be closed because:

1. There is a workaround for our users
2. The proper fix is on Pinata's (the service) side.*
    * *for now, see https://github.com/multiformats/js-multiaddr/issues/310

Please let me know if you feel differently or have been unable to resolve this issue.

**Comment by mariaa144** [comment]
I tried to change the config by removing all the lines with "quic" in them but I still got the error. I edited the `~/.ipfs/config` and then `systemctl --user restart ipfs.service`. It isn't clear to me how to disable the feature tiggering the error.  I'm on version `kubov0.18.1 675f8bddc` of IPFS.

**Comment by SgtPooki** [comment]
@mariaa144 can you share your config with me?

**Comment by mariaa144** [comment]
I tried to remove keys. Let me know if I left anything secret in there. I put back the `quic` lines because they didn't seem to make a difference.
```
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Origin": [
        "https://webui.ipfs.io",
        "http://webui.ipfs.io.ipns.localhost:8080"
      ]
    }
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/quic",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "xxx",
    "PrivKey": "zzz"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {
      "Pinata": {
        "API": {
          "Endpoint": "https://api.pinata.cloud/psa",
          "Key": "xxxx"
        },
        "Policies": {
          "MFS": {
            "Enable": false,
            "PinName": "",
            "RepinInterval": ""
          }
        }
      }
    }
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {},
  "Routing": {
    "Methods": null,
    "Routers": null
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

**Comment by SgtPooki** [comment]
Can you try updating the "Swarm" section in your config to be the following? It's the same as what you get from running `ipfs config Swarm.Transports.Network.WebTransport --json false` 

```json
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {
        "WebTransport": false
      },
      "Security": {}
    }
  }
```

**Comment by mariaa144** [comment]
@SgtPooki I tried the changes in my config, I restarted IPFS but I still got the same errors. Do you have any other suggestions for me to try?

**Comment by SgtPooki** [comment]
That's the best I can think of until Pinata updates or we solve this error.

@lidel do you have any suggestions?

**Comment by mulder1628** [comment]
why is bot keep closing issues not resolved? I hit this error today, and similar issues got resolved with no real solution.
