### ISSUE TITLE
Reopen #1999: Can't resolve the locale

### ISSUE THREAD

**Issue by gnh1201** [ipfs/ipfs-webui#2097]
**Describe the bug**
Can't resolve the locale (Korean, ko, ko-KR), like #1999

**To Reproduce**
If I trying connect the IPFS webui on my computer (with ko-KR locale), it tries to access the wrong address.

**Expected behavior**
It connect to the locale `ko-KR`. `/ipfs/[BAFYHASH]/locales/ko-KR/[FILENAME].json`

**Actual behavior**
It connect to the locale `ko` (it does not exist). `/ipfs/[BAFYHASH]/locales/ko/[FILENAME].json`
As a result, I got this error:
```
ipfs resolve -r /ipfs/[BAFYHASH]/locales/ko/settings.json: no link named "[FILENAME].json" under [BAFYHASH]
```

the `ko` and the `ko-KR` are the same code. It need a proper redirection.

**Comment by SgtPooki** [comment]
FYI that I added some tests for i18n, and have a proper test case that is failing to prove this bug. working on fix now.

**Comment by SgtPooki** [comment]
I can repro the failure when loading via IPFS url at `ipfs://bafybeidxhsjdowd3kgekefq3ezpcektrq7i2i4dnbrrioiwftvksz4oof4/#/welcome` even with `en-US` locales: 

![image](https://user-images.githubusercontent.com/1173416/221019711-f71403d8-90b1-4185-9ebd-bcbb7297264a.png)


the above CID is for a local build I did:

```bash
> npm run build
...
> ipfs add --cid-version 1 -Q -r ./build
bafybeidxhsjdowd3kgekefq3ezpcektrq7i2i4dnbrrioiwftvksz4oof4
```

looking into modifying the i18n-http-backend `loadPath` option so that we are only sending requests for the locales that exist

**Comment by SgtPooki** [comment]
@gnh1201 Can you confirm that things are working properly with the build from the [PR build](https://github.com/ipfs/ipfs-webui/actions/runs/4257768580/jobs/7408314042) ?

Things are loading properly for me, with no misses on locale fetches any longer.

PR: https://github.com/ipfs/ipfs-webui/pull/2102
PR build: https://github.com/ipfs/ipfs-webui/actions/runs/4257768580/jobs/7408314042
CID: bafybeic5stlj7yotwlhy4f4nrcf2g2agtmugey7yc34itjt3qe4bekx3hq
