### ISSUE TITLE
PDF Viewer Refreshes when interacting with webui

### ISSUE THREAD

**Issue by whizzzkid** [ipfs/ipfs-webui#2145]
**Describe the bug**
While interacting with other elements on page, the PDF viewer re-renders.

**To Reproduce**
1. Import a sample PDF in either webui/desktop
2. Try interacting with ui elements around the pdf
3. PDF viewer re-renders.
4. ReRenders can be expensive and based on the size of file it can take longer.

**Expected behavior**
It should not re-render.

**Screenshots**

https://github.com/ipfs/ipfs-webui/assets/1895906/e573131f-c233-48d7-9f52-0558101a2f95

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5 (22G74)
 - Browser Chrome, IPFS - Desktop
 - Version Version 115.0.5790.114 (Official Build) (arm64), webui: https://github.com/ipfs/ipfs-webui/commit/a43dd23

**Additional context**
It looks like it should be fairly straightforward to remove pdf-view updates from the rendering cycle.

**Comment by MattWong-ca** [comment]
Hey @SgtPooki @lidel 

I'm Matt, currently going through Protocol Labs Dev Guild cohort 1. I was able to replicate this on local.

In [FilesPage.js](https://github.com/ipfs/ipfs-webui/blob/main/src/files/FilesPage.js), `MainView` is defined as a new component inside the `FilesPage` component, so clicking UI elements around the PDF re-renders `MainView` (and since `MainView` contains the logic that shows the file preview component, the preview re-renders). Issue seemed to only affect PDFs.

I was able to find a fix by creating and using a new file preview component defined outside of `FilePages`. Will submit a PR!
