### ISSUE TITLE
When I upload a file to IPFS, the shared link does not work properly

### ISSUE THREAD

**Issue by HangreeBee** [ipfs/ipfs-webui#2234]
**Describe the bug**
After uploading a file to IPFS, then get a shared link, then copy and paste to the url to a web browser,
No image and file are showing up to the web browser.

**Screenshots**
![timeout](https://github.com/ipfs/ipfs-webui/assets/163699863/515f1c1e-ad6c-43ab-8338-7938b75669e8)

**Desktop (please complete the following information):**
 - Browser [Chrome and Bing]

**Comment by oreHGA** [comment]
Hey @HangreeBee were you able to fix this? I'm running into a similar error after uploading some csv files to ipfs

**Comment by lidel** [comment]
Thenk you for reporting. 

I am closing issue here, because https://docs.ipfs.tech/concepts/public-utilities/#public-ipfs-gateways are not part of ipfs-webui, but HTTP relay-like servers, provided on best-effort basis.

Please retry, I know [rainbow](https://github.com/ipfs/rainbow/) (backend of [public gateway](https://docs.ipfs.tech/concepts/public-utilities/#public-ipfs-gateways)) received fixes which should help with retrieval from NAT'd peers.
If you experience issues with public goods infra, report issues in https://github.com/ipshipyard/waterworks-community
