### ISSUE TITLE
[Documentation] Files added by webui should not be regarded as pinned

### ISSUE THREAD

**Issue by EliasGabrielsson** [ipfs/ipfs-webui#962]
### Issue:

Files added using the `webui` does not show up while issuing command: `ipfs pin ls`. The files show up in the web ui. According to the documentation for the IPFS HTTP CLIENT - API an added file by the webui shall be pinned by default https://github.com/ipfs/interface-js-ipfs-core/blob/master/SPEC/FILES.md#add. This is not correct, explained in this issue: https://github.com/ipfs/go-ipfs/issues/5981#event-2140798233. 

### Action needed:

* Documentation needs to be be more stringent about what _is stored_ locally on the machine and _not_.
* Maybe even reflect this in the UI somehow. When using the web-ui I thought files added shall be regarded as persistent but that aren't the case apparently.

**Comment by olizilla** [comment]
Files you add via webui are added to your "Mutable File System" (MFS) view over your local blockstore. The MFS view gives you a unix-file-system-like view of things that you can edit, so you can add a file to `/my-file.txt` to your local MFS view, and under the hood, it is chunked and added to added to the blockstore, and then the root CID is added as a link called `myfile.txt` from the `/` directory in your MFS. Because all the things are immutable, the CID for the `/` folder changes, and that new CID becomes your MFS root, and that CID is pinned along with all locally stored CIDs that it links to.

In this way, files you add to webui are added to your MFS and are pinned, transitively. The individual files you add won't show up in the out put of `ipfs pin ls`, as only the current root CID is pinned.

The files you add via webui are stored locally on your machine and will not be garbage collected if you have that enabled.

We defineltly need to simplify the model of how the blockstore, pins and the MFS interact, so it's more obvious to folks. In the meantime @EliasGabrielsson, do you have any thoughts on how we could clarify the docs or UI to better show this?

**Comment by akledirs** [comment]
Maybe show sign "Pinned" in WebUI or do note about this for users? I few days search info about fact pinning my files in webui. Thanks this issue now know.

**Comment by lidel** [comment]
Closing, as a lot happened since 2019:
- support for remote pinning landed: https://github.com/ipfs/ipfs-gui/issues/91 
- we revamped the UI around local pins https://github.com/ipfs/ipfs-webui/issues/1773#issuecomment-828886731 + additional UI allowing for unpinning when a file is removed from MFS (https://github.com/ipfs/ipfs-webui/pull/1644)

Any follow-ups should happen in new issues.
